/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSecretsRouteImport } from './routes/dashboard.secrets'
import { Route as DashboardScaRouteImport } from './routes/dashboard.sca'
import { Route as DashboardSastRouteImport } from './routes/dashboard.sast'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardIacRouteImport } from './routes/dashboard.iac'
import { Route as DashboardFindingsRouteImport } from './routes/dashboard.findings'
import { Route as DashboardDastRouteImport } from './routes/dashboard.dast'
import { Route as DashboardContainerRouteImport } from './routes/dashboard.container'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard.compliance'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecretsRoute = DashboardSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScaRoute = DashboardScaRouteImport.update({
  id: '/sca',
  path: '/sca',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSastRoute = DashboardSastRouteImport.update({
  id: '/sast',
  path: '/sast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIacRoute = DashboardIacRouteImport.update({
  id: '/iac',
  path: '/iac',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFindingsRoute = DashboardFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDastRoute = DashboardDastRouteImport.update({
  id: '/dast',
  path: '/dast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContainerRoute = DashboardContainerRouteImport.update({
  id: '/container',
  path: '/container',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/container': typeof DashboardContainerRoute
  '/dashboard/dast': typeof DashboardDastRoute
  '/dashboard/findings': typeof DashboardFindingsRoute
  '/dashboard/iac': typeof DashboardIacRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/sast': typeof DashboardSastRoute
  '/dashboard/sca': typeof DashboardScaRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/container': typeof DashboardContainerRoute
  '/dashboard/dast': typeof DashboardDastRoute
  '/dashboard/findings': typeof DashboardFindingsRoute
  '/dashboard/iac': typeof DashboardIacRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/sast': typeof DashboardSastRoute
  '/dashboard/sca': typeof DashboardScaRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/container': typeof DashboardContainerRoute
  '/dashboard/dast': typeof DashboardDastRoute
  '/dashboard/findings': typeof DashboardFindingsRoute
  '/dashboard/iac': typeof DashboardIacRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/sast': typeof DashboardSastRoute
  '/dashboard/sca': typeof DashboardScaRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/compliance'
    | '/dashboard/container'
    | '/dashboard/dast'
    | '/dashboard/findings'
    | '/dashboard/iac'
    | '/dashboard/projects'
    | '/dashboard/reports'
    | '/dashboard/sast'
    | '/dashboard/sca'
    | '/dashboard/secrets'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/compliance'
    | '/dashboard/container'
    | '/dashboard/dast'
    | '/dashboard/findings'
    | '/dashboard/iac'
    | '/dashboard/projects'
    | '/dashboard/reports'
    | '/dashboard/sast'
    | '/dashboard/sca'
    | '/dashboard/secrets'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/compliance'
    | '/dashboard/container'
    | '/dashboard/dast'
    | '/dashboard/findings'
    | '/dashboard/iac'
    | '/dashboard/projects'
    | '/dashboard/reports'
    | '/dashboard/sast'
    | '/dashboard/sca'
    | '/dashboard/secrets'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/secrets': {
      id: '/dashboard/secrets'
      path: '/secrets'
      fullPath: '/dashboard/secrets'
      preLoaderRoute: typeof DashboardSecretsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sca': {
      id: '/dashboard/sca'
      path: '/sca'
      fullPath: '/dashboard/sca'
      preLoaderRoute: typeof DashboardScaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sast': {
      id: '/dashboard/sast'
      path: '/sast'
      fullPath: '/dashboard/sast'
      preLoaderRoute: typeof DashboardSastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/iac': {
      id: '/dashboard/iac'
      path: '/iac'
      fullPath: '/dashboard/iac'
      preLoaderRoute: typeof DashboardIacRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/findings': {
      id: '/dashboard/findings'
      path: '/findings'
      fullPath: '/dashboard/findings'
      preLoaderRoute: typeof DashboardFindingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dast': {
      id: '/dashboard/dast'
      path: '/dast'
      fullPath: '/dashboard/dast'
      preLoaderRoute: typeof DashboardDastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/container': {
      id: '/dashboard/container'
      path: '/container'
      fullPath: '/dashboard/container'
      preLoaderRoute: typeof DashboardContainerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardContainerRoute: typeof DashboardContainerRoute
  DashboardDastRoute: typeof DashboardDastRoute
  DashboardFindingsRoute: typeof DashboardFindingsRoute
  DashboardIacRoute: typeof DashboardIacRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSastRoute: typeof DashboardSastRoute
  DashboardScaRoute: typeof DashboardScaRoute
  DashboardSecretsRoute: typeof DashboardSecretsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardContainerRoute: DashboardContainerRoute,
  DashboardDastRoute: DashboardDastRoute,
  DashboardFindingsRoute: DashboardFindingsRoute,
  DashboardIacRoute: DashboardIacRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSastRoute: DashboardSastRoute,
  DashboardScaRoute: DashboardScaRoute,
  DashboardSecretsRoute: DashboardSecretsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
